openapi: 3.1.0
info:
  title: Bookmarks API
  version: 0.0.1
paths:
  /collections:
    get:
      summary: Get collections
      description: Retrieves metadata for all bookmark collections
  /collections/{collection-id}/types:
    get:
      summary: Get types in a collection
      parameters:
      - name: collection-id
        in: path
        required: true
  /collections/{collection-id}/bookmarks/{bookmark-id}:
    get:
      summary: Get bookmarks in a collection
      description: Retrieves bookmarks in the collection
      parameters:
      - name: collection-id
        in: path
        required: true
      - name: bookmark-id
        in: path
        required: false
    patch:
      summary: Update a bookmark
      description: Change something about a bookmark, for example name or URL
      parameters:
      - name: collection-id
        in: path
        required: true
      - name: bookmark-id
        in: path
        required: true
    delete:
      summary: Delete a bookmark
      parameters:
      - name: collection-id
        in: path
        required: true
      - name: bookmark-id
        in: path
        required: true
  /collections/{collection-id}/bookmarks:
    post:
      summary: Add a bookmark to a collection
      parameters:
      - name: collection-id
        in: path
        required: true
  /types/{type-id}:
    patch:
      summary: Change a type
      description: Change something about a type, for example its name
      parameters:
      - name: type-id
        in: path
        required: true
    delete:
      summary: Delete a type from a collection
      description: Deletes all bookmarks of the deleted type
      parameters:
      - name: type-id
        in: path
        required: true
  /bookmarks/{bookmark-id}/tags:
    get:
      summary: Get tags for a bookmark
      description: Get the bookmarks tag-associated with specified bookmark
      parameters:
      - name: bookmark-id
        in: path
        required: true
    post:
      summary: Tag a bookmark with another bookmark
      description: Creates a bidirectional association between the two bookmarks
      parameters:
      - name: bookmark-id
        in: path
        required: true
  /bookmarks/{bookmark-id}/tags/{tag-id}:
    delete:
      summary: Delete a tagging association
      description: Deletes the bidirectional tag association between the two bookmarks
      parameters:
      - name: bookmark-id
        in: path
        required: true
      - name: tag-id
        in: path
        required: true
