openapi: 3.1.0
info:
  title: Bookmarks API
  version: 0.0.1
paths:
  /users:
    post:
      summary: Create a user
      description: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: success
        "422":
          description: email already exists
    put:
      summary: Update a user
      description: Change a user's email or password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: success
  /users/login:
    post:
      summary: Login
      description: Log in a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: success
        "401":
          description: invalid email or password
  /collections:
    get:
      summary: Get collections
      description: Get list of bookmark collections
      responses:
        "200":
          description: List of bookmark collections.
          content:
            application/json:
              schema:
                collections:
                  type: array
                  items:
                    type: object
                    properties:
                      created:
                        type: string
                      id:
                        type: integer
                      name:
                        type: string
  /collections/{collection-id}/types:
    get:
      summary: Get types
      parameters:
      - name: collection-id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: List of bookmark types for the collection.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /collections/{collection-id}/bookmarks/{bookmark-id}:
    get:
      summary: Get a bookmark
      description: Get a bookmark in the specified collection
      parameters:
      - name: collection-id
        in: path
        required: true
        schema:
          type: integer
      - name: bookmark-id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Bookmark.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bookmark'
    patch:
      summary: Update a bookmark
      description: Change something about a bookmark, for example name or URL
      parameters:
      - name: collection-id
        in: path
        required: true
        schema:
          type: integer
      - name: bookmark-id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                link:
                  type: string
                type:
                  type: string
                description:
                  type: string
                note:
                  type: string
                note_is_markdown:
                  type: boolean
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
    delete:
      summary: Delete a bookmark
      parameters:
      - name: collection-id
        in: path
        required: true
        schema:
          type: integer
      - name: bookmark-id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
  /collections/{collection-id}/bookmarks:
    get:
      summary: Get bookmarks
      description: Get bookmarks in the specified collection
      parameters:
      - name: collection-id
        in: path
        required: true
        schema:
          type: integer
      - name: type
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: List of bookmarks for the collection.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/bookmark'
    post:
      summary: Add a bookmark
      parameters:
      - name: collection-id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                link:
                  type: string
                type:
                  type: string
                description:
                  type: string
                note:
                  type: string
                note_is_markdown:
                  type: boolean
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
  /types/{type-id}:
    patch:
      summary: Update a type
      description: Change something about a type, for example its name
      parameters:
      - name: type-id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
    delete:
      summary: Delete a type
      description: Deletes all bookmarks of the deleted type
      parameters:
      - name: type-id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
  /bookmarks/{bookmark-id}/tags:
    get:
      summary: Get tags for a bookmark
      description: Get the bookmarks tag-associated with specified bookmark
      parameters:
      - name: bookmark-id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
    post:
      summary: Tag a bookmark
      description: Tag a bookmark with another bookmark. Creates a bidirectional association between the two bookmarks.
      parameters:
      - name: bookmark-id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tag_bookmark_id:
                  type: integer
      responses:
        "200":
          description: success
        "400":
          description: tag_bookmark_id missing from payload
  /bookmarks/{bookmark-id}/tags/{tag-id}:
    delete:
      summary: Delete a tag
      description: Deletes the bidirectional tag association between two bookmarks.
      parameters:
      - name: bookmark-id
        in: path
        required: true
        schema:
          type: integer
      - name: tag-id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    bookmark:
      type: object
      properties:
        created:
          type: string
        description:
          type: string
        id:
          type: integer
        link:
          type: string
        name:
          type: string
        type:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
        note:
          type: string
        note_is_markdown:
          type: boolean

